/*
 * Automatically generated by jrpcgen 1.0.7 on 9/3/08 7:17 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.epics.ioc.pdrv.vxi11.rpc;
/**
 * A collection of constants used by the "vxi11intr" ONC/RPC program.
 */
public interface vxi11intr {
    public static final int DEVICE_INTR = 0x0607B1;
    public static final int DEVICE_INTR_VERSION = 1;
    public static final int device_intr_srq_1 = 30;
}
// End of vxi11intr.java
